# Site settings
title: Scripted
description: > # this means to ignore newlines until "baseurl:"
  Various learnings and rantings from my experience in software development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bbrock25.github.io" # the base hostname & protocol for your site
github_username:  bbrock25

# Build settings
markdown: kramdown

